---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    run_list:
      - recipe[svalbard-vault::default]
    attributes:
  - name: ca
    data_bags_path: "test/integration/ca/data_bags"
    run_list:
      - recipe[svalbard-vault::ca]
    attributes:
