---
driver:
  name: docker
    use_sudo: false
    dns:
      - 140.107.42.11
      - 140.107.117.11

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[svalbard-vault::default]
    attributes:
