name 'svalbard-vault'
maintainer 'Michael Gutteridge'
maintainer_email 'mrg@fredhutch.org'
license 'all_rights'
description 'Installs/Configures svalbard-vault'
long_description 'Installs/Configures svalbard-vault'
version '0.1.0'

depends 'chef-vault'
depends 'ssl_certificate', '~> 1.11'
depends 'consul-cluster', '~> 2.0'
depends 'hashicorp-vault', '~> 2.4'
