name 'svalbard-vault'
maintainer 'Michael Gutteridge'
maintainer_email 'mrg@fredhutch.org'
license 'all_rights'
description 'Installs/Configures svalbard-vault'
long_description 'Installs/Configures svalbard-vault'
version '0.1.5'

depends 'chef-vault'
depends 'trusted_certificate', '~> 1.0.0'
