default['svalbard-vault']['root_dir'] = '/opt/svalbard'

default['svalbard-vault']['tls']['ssl_key']['path'] = '/etc/vault/ssl/private/vault.key'
default['svalbard-vault']['tls']['ssl_key']['source'] = 'chef-vault'
default['svalbard-vault']['tls']['ssl_key']['bag'] = 'secrets'
default['svalbard-vault']['tls']['ssl_key']['item'] = 'vault'
default['svalbard-vault']['tls']['ssl_key']['item_key'] = 'private_key'
default['svalbard-vault']['tls']['ssl_cert']['path'] = '/etc/vault/ssl/certs/vault.crt'
default['svalbard-vault']['tls']['ssl_cert']['source'] = 'chef-vault'
default['svalbard-vault']['tls']['ssl_cert']['bag'] = 'secrets'
default['svalbard-vault']['tls']['ssl_cert']['item'] = 'vault'
default['svalbard-vault']['tls']['ssl_cert']['item_key'] = 'certificate'
default['svalbard-vault']['tls']['ssl_chain']['path'] = '/etc/vault/ssl/certs/chain.crt'
default['svalbard-vault']['tls']['ssl_chain']['name'] = 'chain.crt'
default['svalbard-vault']['tls']['ssl_chain']['source'] = 'chef-vault'
default['svalbard-vault']['tls']['ssl_chain']['bag'] = 'secrets'
default['svalbard-vault']['tls']['ssl_chain']['item'] = 'vault'
default['svalbard-vault']['tls']['ssl_chain']['item_key'] = 'ca_certificate'
